name: Build

on:
  push:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.16.1"

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Remove .gitignore
        run: rm -f .gitignore

      - name: Commit and push if there are changes
        run: |
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Action"
          git add dist/*
          git push
